[project]
name = "pytauri-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "copier>=9.7.1",
]

[project.scripts]
pytauri-cli = "pytauri_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
